chore: update @actions/artifact for the purposeof uploading the artif…
saurav0705/check-history-action pull request #65
Opened 2024-03-19 06:10 UTC by cwbusacker

…acts sooner

2024-03-19 06:44 UTC, saurav0705 commented
you can skip generating files in dist i have already added a action which updates main when a commit is pushed

2024-03-19 06:46 UTC, saurav0705 requested changes

2024-03-19 06:46 UTC, saurav0705 commented on package-lock.json
remove this file as we use `yarn` as package manager

2024-03-19 06:46 UTC, saurav0705 commented on dist/index.js
remove this file

2024-03-19 06:46 UTC, saurav0705 commented on dist/index.js.map
remove this file

2024-03-19 06:46 UTC, saurav0705 commented on dist/licenses.txt
remove this file

2024-03-19 12:27 UTC, cwbusacker commented
> you can skip generating files in dist i have already added a action which updates main when a commit is pushed



> you can skip generating files in dist i have already added a action which updates main when a commit is pushed

I update dist so that I can test it on a separate branch. How else will I test?

2024-03-20 07:27 UTC, saurav0705 approved these changes

2024-03-20 07:28 UTC, merged